# Generated by Django 3.0.5 on 2020-04-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('numberID', models.IntegerField(primary_key=True, serialize=False)),
                ('subclass', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('category', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('lifecycle', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('incorpDate', models.DateTimeField()),
                ('releaseDate', models.DateTimeField()),
                ('effectivityDate', models.DateTimeField()),
                ('complianceCalculatedDate', models.DateTimeField()),
                ('overallCompliance', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('levelComplianceIndicator', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('complianceRollUp', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('productHierarchy', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('user', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
    ]
