# Generated by Django 2.2.12 on 2020-05-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberID', models.CharField(max_length=15)),
                ('impactedUser', models.CharField(blank=True, max_length=200)),
                ('subclass', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(blank=True, max_length=200)),
                ('summary', models.CharField(blank=True, max_length=200)),
                ('causingCI', models.CharField(blank=True, max_length=200)),
                ('assignedTo', models.CharField(blank=True, max_length=200)),
                ('openDate', models.DateTimeField(null=True)),
                ('assignedDate', models.DateTimeField(null=True)),
                ('resolutionDate', models.DateTimeField(null=True)),
                ('closedDate', models.DateTimeField(null=True)),
                ('scalationDate', models.DateTimeField(null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('issueCategory', models.CharField(blank=True, max_length=200)),
                ('issueReason', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
