# Generated by Django 2.2.12 on 2020-05-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('numberID', models.IntegerField(primary_key=True, serialize=False)),
                ('subclass', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('category', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('lifecycle', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('incorpDate', models.DateTimeField(blank=True, default='2020-01-01 00:00', null=True)),
                ('releaseDate', models.DateTimeField(blank=True, default='2020-01-01 00:00', null=True)),
                ('effectivityDate', models.DateTimeField(blank=True, default='2020-01-01 00:00', null=True)),
                ('complianceCalculatedDate', models.DateTimeField(blank=True, default='2020-01-01 00:00', null=True)),
                ('overallCompliance', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('levelComplianceIndicator', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('complianceRollUp', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('productHierarchy', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('user', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
    ]
