# Generated by Django 2.2.12 on 2020-05-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='complianceCalculatedDate',
            new_name='assignedDate',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='complianceRollUp',
            new_name='assignedTo',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='description',
            new_name='causingCI',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='effectivityDate',
            new_name='closedDate',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='incorpDate',
            new_name='escalationDate',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='levelComplianceIndicator',
            new_name='impactedUser',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='lifecycle',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='releaseDate',
            new_name='openDate',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='overallCompliance',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='productHierarchy',
            new_name='summary',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolutionDate',
            field=models.DateTimeField(blank=True, default='2020-01-01 00:00', null=True),
        ),
    ]
