# Generated by Django 3.0.5 on 2020-04-29 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='complianceCalculatedDate',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='effectivityDate',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='incorpDate',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='releaseDate',
        ),
    ]
