# Generated by Django 3.0.5 on 2020-04-29 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200428_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='complianceCalculatedDate',
            field=models.DateField(blank=True, default='2020-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='effectivityDate',
            field=models.DateField(blank=True, default='2020-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='incorpDate',
            field=models.DateField(blank=True, default='2020-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='releaseDate',
            field=models.DateField(blank=True, default='2020-01-01', null=True),
        ),
    ]
